shop_accounts/urls.py
from django.urls import path

from shop_accounts.views import (
    login_user,
    logout_user,
    register_user,
    user_reset_password,
    user_change_profile,
    user_verify_phone,
    user_send_otp,
    user_profile,
    user_address,
    user_address_detail,
    user_address_delete,
    user_get_cities_of_state,
    user_favorite,
    user_favorite_add,
    user_favorite_delete,
    user_comment,
    user_comment_positive_vote,
    user_comment_negative_vote,
    user_comment_delete,
    user_ticket,
    user_create_ticket,
    user_ticket_detail,
    user_orders,
    user_order_detail,
    LastVisitedView,
)

app_name = 'auth'
urlpatterns = [
    # User Authentication Methods
    path('auth/login', login_user, name='login'),
    path('auth/logout', logout_user, name='logout'),
    path('auth/register', register_user, name='register'),
    path('auth/reset-password', user_reset_password, name='reset-password'),
    # User Profile Methods
    path('account/user-panel', user_profile, name='user-profile'),
    path('account/user-change-profile', user_change_profile, name='change-profile'),
    path('account/user-send-otp', user_send_otp, name='send-otp'),
    path('account/user-verify-phone', user_verify_phone, name='verify-phone'),
    # User Profile Address Methods
    path('account/user-address', user_address, name='user-address'),
    path('account/user-address/<int:address_id>/edit', user_address_detail, name='user-address-edit'),
    path('account/user-address/<int:address_id>/delete', user_address_delete, name='user-address-delete'),
    path('account/user-get-cities-of-state', user_get_cities_of_state, name='user-get-cities-of-state'),
    # User Profile Favorite Methods
    path('account/user-favorite', user_favorite, name='user-favorite'),
    path('account/user-favorite/<slug>/add', user_favorite_add, name='user-favorite-add'),
    path('account/user-favorite/<slug>/delete', user_favorite_delete, name='user-favorite-delete'),
    # User Profile Comment Methods
    path('account/user-comment', user_comment, name='user-comment'),
    path('account/user-comment/<comment_id>/delete', user_comment_delete, name='user-comment-delete'),
    path('account/user-comment/<comment_id>/pos-vote', user_comment_positive_vote, name='user-comment-positive-vote'),
    path('account/user-comment/<comment_id>/neg-vote', user_comment_negative_vote, name='user-comment-negative-vote'),
    # User Profile Ticket Methods
    path('account/ticket', user_ticket, name='user-ticket'),
    path('account/ticket/add', user_create_ticket, name='user-add-ticket'),
    path('account/ticket/<ticket_id>', user_ticket_detail, name='user-ticket-show'),
    # User Orders Methods
    path('account/invoice', user_orders, name='user-invoice'),
    path('account/invoice/<str:order_code>', user_order_detail, name='user-invoice-detail'),
    # User Last Visited Product Methods
    path('recent-visits', LastVisitedView.as_view(), name='recent-visits'),
]

shop_cart/urls.py
from django.urls import path

from shop_cart.views import *

app_name = 'cart'
urlpatterns = [
    path('', cart_view, name='user-cart'),
    path('add/<str:product_code>', cart_add, name='user-cart-add'),
    path('remove/<str:product_code>', cart_remove, name='user-cart-remove'),
]

shop_order/urls.py
from django.urls import path

from shop_order.views import *

app_name = 'order'
urlpatterns = [
    path('check-out', cart_check_out, name='check-out'),
    path('to-bank/<str:order_code>/', to_bank, name='to-bank'),
    path('call-back', call_back, name='call-back'),
]

shop_products/urls.py
from django.urls import path

from .views import (
    search_products_view,
    get_product_amazing,
    detail_product_view,
    get_product_by_brand_view,
    search_product_by_category_view,
)

app_name = 'products'
urlpatterns = [
    path('search/', search_products_view, name='search'),
    path('search/suggested/', get_product_amazing, name='suggested'),
    path('search/<category>', search_product_by_category_view, name='search_by_category'),
    path('search/brand/<brand>', get_product_by_brand_view, name='product_by_brand'),
    path('<product_code>/<product_slug>', detail_product_view, name='detail_product'),
]

tinakala/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.views.decorators.cache import never_cache
from ckeditor_uploader import views as ckeditor_views

from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from .settings import (
    DEBUG,
    STATIC_URL,
    STATIC_ROOT,
    MEDIA_URL,
    MEDIA_ROOT,
)
from .views import (
    home_page,
)

urlpatterns = [
    # reset password urls
    path('password-reset/', PasswordResetView.as_view(
        template_name='accounts/reset_password/password_reset.html'), name='password_reset'),
    path('password-reset/done/', PasswordResetDoneView.as_view(
        template_name='accounts/reset_password/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name='accounts/reset_password/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(
        template_name='accounts/reset_password/password_reset_complete.html'), name='password_reset_complete'),
    # admin panel urls
    path('admin/', admin.site.urls),
    # ckeditor path
    url(r'^ckeditor/upload/', login_required(ckeditor_views.upload), name='ckeditor_upload'),
    url(r'^ckeditor/browse/', never_cache(login_required(ckeditor_views.browse)), name='ckeditor_browse'),
    # main application urls
    path('', home_page, name='home-page'),
    path('', include('shop_accounts.urls', namespace='auth')),
    path('', include('shop_settings.urls', namespace='info')),
    path('', include('shop_contact.urls', namespace='contact')),
    path('blog/', include('shop_blog.urls', namespace='blog')),
    path('products/', include('shop_products.urls', namespace='products')),
    path('cart/', include('shop_cart.urls', namespace='cart')),
    path('order/', include('shop_order.urls', namespace='order')),
]
if DEBUG:
    urlpatterns += static(STATIC_URL, document_root=STATIC_ROOT)
    urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

shop_cart/models.py
from django.db import models

# Create your models here.

shop_cart/forms.py
from django import forms


class AddProductToCart(forms.Form):
    PRODUCT_COUNT_CHOICE = [(i, str(i)) for i in range(1, 6)]
    product_count = forms.TypedChoiceField(required=False, choices=PRODUCT_COUNT_CHOICE, coerce=int,
                                           widget=forms.Select(attrs={
                                               'class': 'form-control'
                                           })
                                           )
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

    def __init__(self, *args, **kwargs):
        self.inventory = kwargs.pop('inventory', None)
        super(AddProductToCart, self).__init__(*args, **kwargs)
        if self.inventory and self.inventory < 5:
            self.fields['product_count'].choices = [(i, str(i)) for i in range(1, self.inventory + 1)]

    def clean_product_count(self):
        product_count = self.cleaned_data.get('product_count')
        print(product_count)
        if product_count:
            if self.inventory < product_count:
                raise forms.ValidationError('درخواست بیشتر از موجودی کالا است!')
            if product_count > 5:
                raise forms.ValidationError('درخواست بیشتر از حد مجاز است!')
        return product_count

shop_cart/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.http import require_POST

from shop_cart.sessions import Cart
from shop_cart.forms import AddProductToCart
from shop_products.models import Product


def cart_view(request):
    cart = Cart(request)
    for item in cart:
        item['update_product_count_form'] = AddProductToCart(
            initial={
                'product_count': item['product_count'],
                'update': True,
            }, inventory=item['product'].inventory)
    context = {
        'cart': cart,
    }
    return render(request, 'cart/SiteCartDetail.html', context)


@require_POST
def cart_add(request, product_code):
    cart = Cart(request)
    product = get_object_or_404(Product, code=product_code)
    form = AddProductToCart(request.POST, inventory=product.inventory)
    if form.is_valid():
        if product.status:
            data = form.cleaned_data
            if not data['product_count']:
                data['product_count'] = 1
            cart.add(product=product, product_count=data['product_count'], update_count=data['update'])
        else:
            cart.remove(product)
    return redirect('cart:user-cart')


def cart_remove(request, product_code):
    cart = Cart(request)
    product = get_object_or_404(Product, code=product_code)
    cart.remove(product)
    return redirect('cart:user-cart')

shop_cart/templates/cart/SiteCartDetail.html
{% extends 'app_site/shared/_SiteMainLayout.html' %}
{% load static %}
{% block content %}
    <main class="main-content dt-sl mt-4 mb-3" style="transform: none;">
        <div class="container main-container" style="transform: none;">

            <div class="row" style="transform: none;">
                {% if cart %}
                    <div class="col-xl-9 col-lg-8 col-md-12 col-sm-12 mb-2 px-0">
                        <nav class="tab-cart-page">
                            <div class="nav nav-tabs" id="nav-tab" role="tablist">
                                <a class="nav-item nav-link active" id="nav-home-tab" data-toggle="tab" href="#nav-home" role="tab" aria-controls="nav-home" aria-selected="true">
                                    سبد خرید<span class="count-cart">{{ cart|length }}</span>
                                </a>
                            </div>
                        </nav>
                    </div>
                {% endif %}
                <div class="col-12" style="transform: none;">
                    {% if cart %}
                        <div class="tab-content" id="nav-tabContent" style="transform: none;">
                            <div class="tab-pane fade show active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab" style="transform: none;">
                                <div class="row" style="transform: none;">
                                    <div class="col-xl-9 col-lg-8 col-12 px-0">
                                        <div class="table-responsive checkout-content dt-sl">
                                            <table class="table table-cart">
                                                <tbody>
                                                {% for item in cart %}
                                                    {% with product=item.product %}

                                                        <tr class="checkout-item">
                                                            <td>
                                                                <img style="width: 100px;height: 100px" src="{{ product.avatar.url }}" alt="">
                                                                <a href="{% url 'cart:user-cart-remove' item.product.code %}" class="checkout-btn-remove">×</a>
                                                            </td>
                                                            <td class="text-right">
                                                                <a href="{% url 'products:detail_product' product.code product.slug %}">
                                                                    <h3 class="checkout-title">
                                                                        {{ product.title|truncatechars:45 }}
                                                                    </h3>
                                                                </a>
                                                                <p class="checkout-dealer">
                                                                    قیمت: {{ item.nice_price }} تومان × {{ item.product_count }}
                                                                </p>
                                                            </td>
                                                            <td>
                                                                <p class="mb-0">تعداد</p>
                                                                <form action="{% url 'cart:user-cart-add' product.code %}" method="post">
                                                                    {% csrf_token %}
                                                                    <div class="row justify-content-center">
                                                                        <div class="mt-1">
                                                                            {{ item.update_product_count_form.product_count }}
                                                                            {{ item.update_product_count_form.update }}
                                                                        </div>
                                                                        {% for error in item.update_product_count_form.update.errors %}
                                                                            <p class="text-danger">{{ error }}</p>
                                                                        {% endfor %}

                                                                        <div>
                                                                            <button class="btn btn-sm btn-primary mr-1 mt-1" type="submit"><i class="mdi mdi-update"></i></button>
                                                                        </div>
                                                                    </div>
                                                                </form>
                                                            </td>
                                                            <td><strong>{{ item.nice_total_price }} تومان</strong></td>
                                                        </tr>

                                                    {% endwith %}
                                                {% endfor %}
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                    <div class="col-xl-3 col-lg-4 col-12 w-res-sidebar" style="position: relative; overflow: visible; box-sizing: border-box; min-height: 1px;">


                                        <div class="theiaStickySidebar" style="padding-top: 0px; padding-bottom: 1px; position: static; transform: none;"><div class="dt-sn mb-2">
                                            <ul class="checkout-summary-summary">
                                                <li>
                                                    <span>مبلغ کل ({{ cart|length }} کالا)</span><span>{{ cart.get_nice_total_price }} تومان</span>
                                                </li>
                                                <li class="checkout-summary-discount">
                                                    <span>امتیاز شما از خرید</span>
                                                    <span>
                                                        <span></span>
                                                        {{ cart.get_point_shop }}
                                                        امتیاز
                                                    </span>
                                                </li>
                                            </ul>
                                            <div class="checkout-summary-devider">
                                                <div></div>
                                            </div>
                                            <div class="checkout-summary-content">
                                                <div class="checkout-summary-price-title">مبلغ قابل پرداخت:</div>
                                                <div class="checkout-summary-price-value">
                                                    <span class="checkout-summary-price-value-amount">{{ cart.get_nice_total_price }}</span>
                                                    تومان
                                                </div>
                                                <a href="{% url 'order:check-out' %}" class="mb-2 d-block">
                                                    <button class="btn-primary-cm btn-with-icon w-100 text-center pr-0">
                                                        <i class="mdi mdi-arrow-left"></i>
                                                        ادامه ثبت سفارش
                                                    </button>
                                                </a>
                                                <div>
                                                    <span>
                                                        کالاهای موجود در سبد شما ثبت و رزرو نشده‌اند، برای ثبت سفارش
                                                        مراحل بعدی را تکمیل کنید.
                                                    </span>
                                                    <span class="help-sn" data-toggle="tooltip" data-html="true" data-placement="bottom" title="" data-original-title="<div class='help-container is-right'><div class='help-arrow'></div><p class='help-text'>محصولات موجود در سبد خرید شما تنها در صورت ثبت و پرداخت سفارش برای شما رزرو می‌شوند. در صورت عدم ثبت سفارش، دیجی‌کالا هیچگونه مسئولیتی در قبال تغییر قیمت یا موجودی این کالاها ندارد.</p></div>">
                                                        <span class="mdi mdi-information-outline"></span>
                                                    </span></div>
                                            </div>
                                        </div><div class="dt-sn checkout-feature-aside pt-4">
                                            <ul>
                                                <li class="checkout-feature-aside-item">
                                                    <img src="{% static 'app_site/img/svg/return-policy.svg' %}" alt="">
                                                    هفت روز ضمانت تعویض
                                                </li>
                                                <li class="checkout-feature-aside-item">
                                                    <img src="{% static 'app_site/img/svg/payment-terms.svg' %}" alt="">
                                                    پرداخت در محل با کارت بانکی
                                                </li>
                                                <li class="checkout-feature-aside-item">
                                                    <img src="{% static 'app_site/img/svg/delivery.svg' %}" alt="">
                                                    تحویل اکسپرس
                                                </li>
                                            </ul>
                                        </div>
                                            <div class="resize-sensor" style="position: absolute; left: 0px; top: 0px; right: 0px; bottom: 0px; overflow: hidden; z-index: -1; visibility: hidden;">
                                                <div class="resize-sensor-expand" style="position: absolute; left: 0; top: 0; right: 0; bottom: 0; overflow: hidden; z-index: -1; visibility: hidden;">
                                                    <div style="position: absolute; left: 0px; top: 0px; transition: all 0s ease 0s; width: 360px; height: 590px;"></div>
                                                </div>
                                                <div class="resize-sensor-shrink" style="position: absolute; left: 0; top: 0; right: 0; bottom: 0; overflow: hidden; z-index: -1; visibility: hidden;">
                                                    <div style="position: absolute; left: 0; top: 0; transition: 0s; width: 200%; height: 200%"></div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% else %}
                        <div class="container main-container">

                            <div class="row">
                                <div class="col-12">
                                    <div class="dt sl dt-sn pt-3 pb-5">
                                        <div class="cart-page cart-empty">
                                            <div class="circle-box-icon"><i class="mdi mdi-cart-remove"></i></div>
                                            <p class="cart-empty-title">سبد خرید شما خالیست!</p>
                                            <p>می‌توانید برای مشاهده محصولات بیشتر به صفحات زیر بروید:</p>
                                            <div class="cart-empty-links mb-5">
                                                <a href="{% url 'auth:user-favorite' %}" class="border-bottom-dt">لیست مورد علاقه من</a>
                                                <a href="#" class="border-bottom-dt">محصولات پرفروش</a>
                                            </div>
                                            <a href="{% url 'home-page' %}" class="btn-primary-cm">ادامه خرید در تیناکالا</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endif %}
                </div>
            </div>

        </div>
    </main>
{% endblock %}