shop_accounts/urls.py
from django.urls import path

from shop_accounts.views import (
    login_user,
    logout_user,
    register_user,
    user_reset_password,
    user_change_profile,
    user_verify_phone,
    user_send_otp,
    user_profile,
    user_address,
    user_address_detail,
    user_address_delete,
    user_get_cities_of_state,
    user_favorite,
    user_favorite_add,
    user_favorite_delete,
    user_comment,
    user_comment_positive_vote,
    user_comment_negative_vote,
    user_comment_delete,
    user_ticket,
    user_create_ticket,
    user_ticket_detail,
    user_orders,
    user_order_detail,
    LastVisitedView,
)

app_name = 'auth'
urlpatterns = [
    # User Authentication Methods
    path('auth/login', login_user, name='login'),
    path('auth/logout', logout_user, name='logout'),
    path('auth/register', register_user, name='register'),
    path('auth/reset-password', user_reset_password, name='reset-password'),
    # User Profile Methods
    path('account/user-panel', user_profile, name='user-profile'),
    path('account/user-change-profile', user_change_profile, name='change-profile'),
    path('account/user-send-otp', user_send_otp, name='send-otp'),
    path('account/user-verify-phone', user_verify_phone, name='verify-phone'),
    # User Profile Address Methods
    path('account/user-address', user_address, name='user-address'),
    path('account/user-address/<int:address_id>/edit', user_address_detail, name='user-address-edit'),
    path('account/user-address/<int:address_id>/delete', user_address_delete, name='user-address-delete'),
    path('account/user-get-cities-of-state', user_get_cities_of_state, name='user-get-cities-of-state'),
    # User Profile Favorite Methods
    path('account/user-favorite', user_favorite, name='user-favorite'),
    path('account/user-favorite/<slug>/add', user_favorite_add, name='user-favorite-add'),
    path('account/user-favorite/<slug>/delete', user_favorite_delete, name='user-favorite-delete'),
    # User Profile Comment Methods
    path('account/user-comment', user_comment, name='user-comment'),
    path('account/user-comment/<comment_id>/delete', user_comment_delete, name='user-comment-delete'),
    path('account/user-comment/<comment_id>/pos-vote', user_comment_positive_vote, name='user-comment-positive-vote'),
    path('account/user-comment/<comment_id>/neg-vote', user_comment_negative_vote, name='user-comment-negative-vote'),
    # User Profile Ticket Methods
    path('account/ticket', user_ticket, name='user-ticket'),
    path('account/ticket/add', user_create_ticket, name='user-add-ticket'),
    path('account/ticket/<ticket_id>', user_ticket_detail, name='user-ticket-show'),
    # User Orders Methods
    path('account/invoice', user_orders, name='user-invoice'),
    path('account/invoice/<str:order_code>', user_order_detail, name='user-invoice-detail'),
    # User Last Visited Product Methods
    path('recent-visits', LastVisitedView.as_view(), name='recent-visits'),
]

shop_products/urls.py
from django.urls import path

from .views import (
    search_products_view,
    get_product_amazing,
    detail_product_view,
    get_product_by_brand_view,
    search_product_by_category_view,
)

app_name = 'products'
urlpatterns = [
    path('search/', search_products_view, name='search'),
    path('search/suggested/', get_product_amazing, name='suggested'),
    path('search/<category>', search_product_by_category_view, name='search_by_category'),
    path('search/brand/<brand>', get_product_by_brand_view, name='product_by_brand'),
    path('<product_code>/<product_slug>', detail_product_view, name='detail_product'),
]

tinakala/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.views.decorators.cache import never_cache
from ckeditor_uploader import views as ckeditor_views

from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from .settings import (
    DEBUG,
    STATIC_URL,
    STATIC_ROOT,
    MEDIA_URL,
    MEDIA_ROOT,
)
from .views import (
    home_page,
)

urlpatterns = [
    # reset password urls
    path('password-reset/', PasswordResetView.as_view(
        template_name='accounts/reset_password/password_reset.html'), name='password_reset'),
    path('password-reset/done/', PasswordResetDoneView.as_view(
        template_name='accounts/reset_password/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name='accounts/reset_password/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(
        template_name='accounts/reset_password/password_reset_complete.html'), name='password_reset_complete'),
    # admin panel urls
    path('admin/', admin.site.urls),
    # ckeditor path
    url(r'^ckeditor/upload/', login_required(ckeditor_views.upload), name='ckeditor_upload'),
    url(r'^ckeditor/browse/', never_cache(login_required(ckeditor_views.browse)), name='ckeditor_browse'),
    # main application urls
    path('', home_page, name='home-page'),
    path('', include('shop_accounts.urls', namespace='auth')),
    path('', include('shop_settings.urls', namespace='info')),
    path('', include('shop_contact.urls', namespace='contact')),
    path('blog/', include('shop_blog.urls', namespace='blog')),
    path('products/', include('shop_products.urls', namespace='products')),
    path('cart/', include('shop_cart.urls', namespace='cart')),
    path('order/', include('shop_order.urls', namespace='order')),
]
if DEBUG:
    urlpatterns += static(STATIC_URL, document_root=STATIC_ROOT)
    urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

shop_accounts/views/views_address.py
"""
shop_accounts -> views -> user address methods
"""
from django.http import JsonResponse, Http404
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods

from shop_settings.models import City
from tinakala.utils import profile_completion_required

from shop_accounts.models import (
    UserProfile,
    UserAddress,
)
from shop_accounts.forms import (
    UserAddressForm,
)

"""
shop_accounts -> profile address load/create methods
"""


@login_required(login_url='auth:login')
@profile_completion_required(profile_model=UserProfile, redirected_path='auth:change-profile')
def user_address(request):
    address_form = UserAddressForm(request.POST or None, request=request)
    active_addresses: UserAddress = UserAddress.objects.filter(user_id=request.user.id, is_active=True)
    if address_form.is_valid():
        user_new_address = UserAddress.objects.create(
            user=request.user,
            fullname=address_form.cleaned_data.get('fullname'),
            phone=address_form.cleaned_data.get('phone'),
            state=address_form.cleaned_data.get('state'),
            city=address_form.cleaned_data.get('city'),
            address=address_form.cleaned_data.get('address'),
            postal_code=address_form.cleaned_data.get('postal_code'),
            plaque=address_form.cleaned_data.get('plaque'),
        )
        user_new_address.save()
        address_form = UserAddressForm()
        messages.success(request, 'آدرس شما با موفقیت ثبت شد.')
        return redirect('auth:user-address')
    context = {
        'active_addresses': active_addresses,
        'address_form': address_form,
    }
    return render(request, 'accounts/SiteAddress.html', context)


@require_http_methods(['GET', ])
@login_required(login_url='auth:login')
@profile_completion_required(profile_model=UserProfile, redirected_path='auth:change-profile')
def user_get_cities_of_state(request):
    state_id = request.GET.get('state_id')
    cities = City.objects.filter(state_id=state_id).order_by('city').values()
    return JsonResponse(list(cities), safe=False)


"""
shop_accounts -> profile address updating methods
"""


@login_required(login_url='auth:login')
@profile_completion_required(profile_model=UserProfile, redirected_path='auth:change-profile')
def user_address_detail(request, address_id):
    address: UserAddress = get_object_or_404(klass=UserAddress, pk=address_id, is_active=True, user=request.user)
    address_form = UserAddressForm(request.POST or None, request=request, initial={
        'fullname': address.fullname,
        'phone': address.phone,
        'state': address.state,
        'city': address.city,
        'address': address.address,
        'postal_code': address.postal_code,
        'plaque': address.plaque,
    })
    if address_form.is_valid():
        address.fullname = address_form.cleaned_data.get('fullname')
        address.phone = address_form.cleaned_data.get('phone')
        address.state = address_form.cleaned_data.get('state')
        address.city = address_form.cleaned_data.get('city')
        address.address = address_form.cleaned_data.get('address')
        address.postal_code = address_form.cleaned_data.get('postal_code')
        address.plaque = address_form.cleaned_data.get('plaque')
        address.is_active = True
        address.save()
        messages.success(request, 'بروزرسانی آدرس با موفقیت انجام شد.')
        return redirect('auth:user-address')
    context = {
        'address_id': address.id,
        'address_form': address_form,
    }
    return render(request, 'accounts/SiteAddressDetail.html', context)


@login_required(login_url='auth:login')
@profile_completion_required(profile_model=UserProfile, redirected_path='auth:change-profile')
def user_address_delete(request, address_id):
    address: UserAddress = get_object_or_404(klass=UserAddress, pk=address_id)
    if address.user != request.user:
        return Http404('آدرسی با این مشخصات برای شما وجود ندارد.')
    address.is_active = False
    address.save()
    messages.success(request, 'آدرس شما با موفقیت حذف شد.')
    return redirect('auth:user-address')

shop_accounts/views/views_comment.py
"""
shop_accounts -> views -> user comment manager methods
"""
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.shortcuts import render, get_object_or_404, redirect

from pure_pagination import Paginator, PageNotAnInteger

from shop_accounts.models import UserProfile, UserCommentVote
from shop_products.models import ProductComment
from tinakala.utils import profile_completion_required, get_total_average


@login_required(login_url='auth:login')
@profile_completion_required(profile_model=UserProfile, redirected_path='auth:change-profile')
def user_comment(request):
    try:
        page = request.GET.get('page', 1)
    except PageNotAnInteger:
        page = 1

    comments = []
    for comment in ProductComment.objects.filter(user=request.user, promote=True):
        total_avg = ProductComment.objects.filter(product=comment.product).values_list('worth', 'quality', 'function')
        comments.append({
            'id': comment.id,
            'title': comment.title,
            'comment': comment.comment,
            'verified': comment.verified,
            'positive': comment.usercommentvote_set.filter(vote=True).count(),
            'negative': comment.usercommentvote_set.filter(vote=False).count(),
            'product_code': comment.product.code,
            'product_slug': comment.product.slug,
            'product_avatar': comment.product.avatar.url,
            'product_avg': get_total_average(total_avg),
        })

    context = {
        'comments': Paginator(comments, request=request, per_page=8).page(page),
    }
    return render(request, 'accounts/SiteUserComment.html', context)


@login_required(login_url='auth:login')
@profile_completion_required(profile_model=UserProfile, redirected_path='auth:change-profile')
def user_comment_delete(request, *args, **kwargs):
    comment_id = kwargs.get('comment_id')
    comment = get_object_or_404(ProductComment, id=comment_id)
    if not comment.promote:
        raise Http404('کامنتی یافت نشد')
    comment.promote = False
    comment.save()
    messages.success(request, f'نظر شما با موفقیت حذف شد.')
    return redirect('auth:user-comment')


@login_required(login_url='auth:login')
@profile_completion_required(profile_model=UserProfile, redirected_path='auth:change-profile')
def user_comment_positive_vote(request, *args, **kwargs):
    comment_id = kwargs.get('comment_id')
    comment = get_object_or_404(ProductComment, id=comment_id)
    existed_user_vote: UserCommentVote = UserCommentVote.objects.filter(user=request.user, comment=comment).first()
    if existed_user_vote:
        existed_user_vote.positive_comment_vote()
    else:
        existed_user_vote = UserCommentVote.objects.create(user=request.user, comment=comment, vote=True)
        existed_user_vote.save()
    messages.success(request, f'نظر مثبت شما برای کامنت ({comment.user.get_full_name()}) با موفقیت ثبت شد.')
    return redirect('auth:user-profile')


@login_required(login_url='auth:login')
@profile_completion_required(profile_model=UserProfile, redirected_path='auth:change-profile')
def user_comment_negative_vote(request, *args, **kwargs):
    comment_id = kwargs.get('comment_id')
    comment = get_object_or_404(ProductComment, id=comment_id)
    existed_user_vote: UserCommentVote = UserCommentVote.objects.filter(user=request.user, comment=comment).first()
    if existed_user_vote:
        existed_user_vote.negative_comment_vote()
    else:
        existed_user_vote = UserCommentVote.objects.create(user=request.user, comment=comment, vote=False)
        existed_user_vote.save()
    messages.success(request, f'نظر منفی شما برای کامنت ({comment.user.get_full_name()}) با موفقیت ثبت شد.')
    return redirect('auth:user-profile')

shop_accounts/views/views_favorite.py
"""
shop_accounts -> views -> user favorite methods
"""
from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from pure_pagination import Paginator, PageNotAnInteger

from shop_accounts.models import UserProfile, UserFavorite
from shop_products.models import Product, ProductComment
from tinakala.utils import profile_completion_required, create_products_object_list


@login_required(login_url='auth:login')
@profile_completion_required(profile_model=UserProfile, redirected_path='auth:change-profile')
def user_favorite(request, *args, **kwargs):
    try:
        page = request.GET.get('page', 1)
    except PageNotAnInteger:
        page = 1

    favorites: UserFavorite = UserFavorite.objects.filter(user=request.user, product__is_active=True).first()
    favorites = create_products_object_list(favorites.product.all(), model=ProductComment) if favorites else []

    context = {
        'favorites': Paginator(favorites, per_page=10, request=request).page(page),
    }
    return render(request, 'accounts/SiteUserFavorite.html', context)


@login_required(login_url='auth:login')
@profile_completion_required(profile_model=UserProfile, redirected_path='auth:change-profile')
def user_favorite_add(request, *args, **kwargs):
    slug = kwargs['slug']
    product = Product.objects.filter(slug=slug).first()
    if product:
        user_favorite_object: UserFavorite = UserFavorite.objects.filter(user=request.user).first()
        if user_favorite_object:
            user_favorite_object.product.add(product)
            user_favorite_object.save()
            message = 'این کالا با موفقیت به لیست علاقه مندی شما اضافه شد.'
        else:
            user_favorite_object = UserFavorite.objects.create(user=request.user)
            user_favorite_object.product.add(product)
            user_favorite_object.save()
            message = 'این کالا با موفقیت به لیست علاقه مندی شما اضافه شد.'
        result = True
    else:
        result = False
        message = f'کالایی با عنوان <<{slug}>> یافت نشد.'
    return JsonResponse([message, result], safe=False)


@login_required(login_url='auth:login')
@profile_completion_required(profile_model=UserProfile, redirected_path='auth:change-profile')
def user_favorite_delete(request, *args, **kwargs):
    slug = kwargs['slug']
    favorite: UserFavorite = get_object_or_404(UserFavorite, user=request.user)
    product = get_object_or_404(Product, slug=slug)
    if favorite:
        favorite.product.remove(product)
        favorite.save()
        messages.success(request, f'کالای <<{product.title}>> از لیست علاقه مندی با موفقیت حذف گردید.')
    else:
        messages.error(request, f'کالایی با عنوان {slug} در لیست علاقه مندی شما موجود نمی باشد.')
    return redirect('auth:user-favorite')

shop_accounts/views/views_visited.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView

from pure_pagination import PaginationMixin

from shop_products.models import ProductVisit


class LastVisitedView(PaginationMixin, LoginRequiredMixin, ListView):
    template_name = 'accounts/SiteUserLastVisited.html'
    paginate_by = 10

    def get_queryset(self):
        return ProductVisit.objects.get_product_by_user(user=self.request.user)[:8]

shop_accounts/templates/accounts/component/profile_user_favorite.html
{% load static %}
<div class="col-xl-6 col-lg-12">
    <div class="px-3">
        <div class="section-title text-sm-title title-wide mb-1 no-after-title-wide dt-sl mb-2">
            <h2>لیست آخرین علاقه‌مندی‌ها</h2>
        </div>
        <div class="profile-section dt-sl">
            <ul class="list-favorites">
                {% if favorites %}
                    {% for favorite in favorites %}
                        <li>
                            <a href="{% url 'products:detail_product' favorite.code favorite.slug %}">
                                <img src="{{ favorite.avatar.url }}" alt="">
                                <span>{{ favorite.title|truncatechars:25 }}</span>
                            </a>
                            <button>
                                <a href="{% url 'auth:user-favorite-delete' favorite.slug %}" class="text-white">
                                    <i class="mdi mdi-trash-can-outline"></i>
                                </a>

                            </button>
                        </li>
                    {% endfor %}
                {% else %}
                    <div class="alert alert-warning">شما محصول فعالی در این بخش ندارید.</div>
                {% endif %}
            </ul>
            <div class="profile-section-link">
                <a href="{% url 'auth:user-favorite' %}" class="border-bottom-dt">
                    <i class="mdi mdi-square-edit-outline"></i>
                    مشاهده و ویرایش لیست مورد علاقه
                </a>
            </div>
        </div>
    </div>
</div>

shop_accounts/templates/accounts/component/profile_user_info.html
{% load jalali_tags %}
<div class="col-xl-6 col-lg-12">
    <div class="px-3">
        <div class="section-title text-sm-title title-wide mb-1 no-after-title-wide dt-sl mb-2">
            <h2>اطلاعات شخصی</h2>
        </div>
        <div class="profile-section dt-sl">
            <div class="row">
                <div class="col-md-6 col-sm-12">
                    <div class="label-info">
                        <span>نام و نام خانوادگی:</span>
                    </div>
                    <div class="value-info">
                        <span>{{ user.get_full_name }}</span>
                    </div>
                </div>
                <div class="col-md-6 col-sm-12">
                    <div class="label-info">
                        <span>پست الکترونیک:</span>
                    </div>
                    <div class="value-info">
                        <span>{{ request.user.email }}</span>
                    </div>
                </div>
                <div class="col-md-6 col-sm-12">
                    <div class="label-info">
                        <span>شماره تلفن همراه:</span>
                    </div>
                    <div class="value-info">
                        <span>{{ user.phone }}</span>
                    </div>
                </div>
                <div class="col-md-6 col-sm-12">
                    <div class="label-info">
                        <span>شماره همراه تایید شده:</span>
                    </div>
                    <div class="value-info">
                        <span>{{ user.phone_verify|yesno:"بلی," }}</span>
                        {% if not user.phone_verify %}
                            <a class="badge badge-info" href="{% url 'auth:verify-phone' %}">
                                <span class="p-1" style="font-size: 11px">شماره همراه شما تایید نشده است</span>
                            </a>
                        {% endif %}
                    </div>
                </div>
                <div class="col-md-6 col-sm-12">
                    <div class="label-info">
                        <span>کد ملی:</span>
                    </div>
                    <div class="value-info">
                        <span>{{ user.national_code }}</span>
                    </div>
                </div>
                <div class="col-md-6 col-sm-12">
                    <div class="label-info">
                        <span>جنسیت کاربر:</span>
                    </div>
                    <div class="value-info">
                        <span>{% if user.gender is 1 %}مرد{% else %}زن{% endif %}</span>
                    </div>
                </div>
                <div class="col-md-6 col-sm-12">
                    <div class="label-info">
                        <span>تاریخ تولد:</span>
                    </div>
                    <div class="value-info">
                        <span>{{ user.birth_day|to_jalali:'%Y/%m/%d' }}</span>
                    </div>
                </div>
            </div>
            <div class="profile-section-link">
                <a href="{% url 'auth:change-profile' %}" class="border-bottom-dt">
                    <i class="mdi mdi-account-edit-outline"></i>
                    ویرایش اطلاعات شخصی
                </a>
            </div>
        </div>
    </div>
</div>

shop_accounts/templates/accounts/component/profile_user_last_orders.html
{% load jalali_tags %}
{% if orders %}
    <div class="row mt-2">
        <div class="col-12">
            <div class="section-title text-sm-title title-wide mb-1 no-after-title-wide dt-sl mb-2 px-res-1">
                <h2>آخرین سفارش‌ها</h2>
            </div>
            <div class="dt-sl">
                <div class="table-responsive">
                    <table class="table table-order">
                        <thead>
                        <tr>
                            <th>ردیف</th>
                            <th>شماره سفارش</th>
                            <th>تاریخ ثبت سفارش</th>
                            <th>مبلغ کل</th>
                            <th>عملیات پرداخت</th>
                            <th>وضعیت سفارش</th>
                            <th>جزییات</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for order in orders %}
                            <tr>
                                <td>{{ order.id }}</td>
                                <td>{{ order.detail.order_code|upper }}</td>
                                <td>{{ order.detail.order_date|to_jalali:'%Y/%m/%d' }}</td>
                                <td>{{ order.detail.get_nice_total_price }} تومان</td>
                                <td><div class="badge badge-{{ order.detail.is_paid|yesno:'success,danger' }}">{{ order.detail.is_paid|yesno:'پرداخت شده,پرداخت نشده' }}</div></td>
                                <td><div class="badge badge-{% if order.detail.transaction.status %}primary{% else %}secondary{% endif %}">
                                    {% if order.detail.transaction.status %}
                                    {% else %}
                                        سفارش پرداخت نشده
                                    {% endif %}
                                </div></td>
                                <td class="details-link">
                                    <a href="{% url 'auth:user-invoice-detail' order.detail.order_code %}">
                                        <i class="mdi mdi-chevron-left"></i>
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}

                        <tr>
                            <td class="link-to-orders" colspan="7">
                                <a href="{% url 'auth:user-invoice' %}">
                                    مشاهده لیست سفارش ها
                                </a>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endif %}

shop_accounts/templates/accounts/component/profile_user_panel.html
{% load static %}
<div class="dt-sl dt-sn mb-3">
    <div class="profile-sidebar-header dt-sl">
        <div class="profile-avatar float-right">
            <img src="{% if user.avatar %}{{ user.avatar.url }}{% else %}{% static 'app_site/img/theme/404.gif' %}{% endif %}" alt="">
        </div>
        <div class="profile-header-content mr-3 mt-2 float-right">
            <span class="d-block profile-username">{{ user.get_full_name }}</span>
            <span class="d-block profile-phone">{{ user.phone }}</span>
        </div>
        <div class="profile-point mt-3 mb-2 dt-sl">
            <span class="float-right label-profile-point">امتیاز شما:</span>
            <span class="float-left value-profile-point">{{ user.point }}</span>
        </div>
        <div class="profile-link mt-2 dt-sl">
            <div class="row">
                <div class="col-6 text-center">
                    <a href="{% url 'auth:reset-password' %}">
                        <i class="mdi mdi-lock-reset"></i>
                        <span class="d-block">تغییر رمز</span>
                    </a>
                </div>
                <div class="col-6 text-center">
                    <a href="{% url 'auth:logout' %}">
                        <i class="mdi mdi-logout-variant"></i>
                        <span class="d-block">خروج از حساب</span>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>

shop_accounts/templates/accounts/component/profile_user_sidebar_menu.html
{% url 'auth:user-profile' as url_user_profile %}
{% url 'auth:user-invoice' as url_user_invoice %}
{% url 'auth:user-ticket' as url_user_ticket %}
{% url 'auth:user-favorite' as url_user_favorite %}
{% url 'auth:user-comment' as url_user_comment %}
{% url 'auth:user-address' as url_user_address %}
{% url 'auth:recent-visits' as url_user_recent_visits %}
{% url 'auth:change-profile' as url_user_change_profile %}

<div class="dt-sl dt-sn mb-3">
    <div class="profile-menu-section dt-sl">
        <div class="label-profile-menu mt-2 mb-2">
            <span>حساب کاربری شما</span>
        </div>
        <div class="profile-menu">
            <ul>
                <li>
                    <a href="{{ url_user_profile }}" {% if request.get_full_path == url_user_profile %}class="active"{% endif %}>
                        <i class="mdi mdi-account-circle-outline"></i>
                        پروفایل
                    </a>
                </li>
                <li>
                    <a href="{{ url_user_invoice }}" {% if request.get_full_path == url_user_invoice %}class="active"{% endif %}>
                        <i class="mdi mdi-basket"></i>
                        همه سفارش ها
                    </a>
                </li>
                <li>
                    <a href="{{ url_user_ticket }}" {% if request.get_full_path == url_user_ticket %}class="active"{% endif %}>
                        <i class="mdi mdi-mailbox-open-outline"></i>
                        تیکت ها
                    </a>
                </li>
                <li>
                    <a href="{{ url_user_favorite }}" {% if request.get_full_path == url_user_favorite %}class="active"{% endif %}>
                        <i class="mdi mdi-heart-outline"></i>
                        لیست علاقمندی ها
                    </a>
                </li>
                <li>
                    <a href="{{ url_user_comment }}" {% if request.get_full_path == url_user_comment %}class="active"{% endif %}>
                        <i class="mdi mdi-glasses"></i>
                         نظرات من
                    </a>
                </li>
                <li>
                    <a href="{{ url_user_address }}" {% if request.get_full_path == url_user_address %}class="active"{% endif %}>
                        <i class="mdi mdi-sign-direction"></i>
                        آدرس ها
                    </a>
                </li>
                <li>
                    <a href="{{ url_user_recent_visits }}" {% if request.get_full_path == url_user_recent_visits %}class="active"{% endif %}>
                        <i class="mdi mdi-eye-outline"></i>
                        بازدیدهای اخیر
                    </a>
                </li>
                <li>
                    <a href="{{ url_user_change_profile }}" {% if request.get_full_path == url_user_change_profile %}class="active"{% endif %}>
                        <i class="mdi mdi-account-edit-outline"></i>
                        اطلاعات شخصی
                    </a>
                </li>
            </ul>
        </div>
    </div>
</div>