shop_blog/urls.py
from django.urls import path

from .views import (
    BlogsView,
    SearchBlogsView,
    BlogsViewByCategoriesOrTags,
    blog_detail_view,
)


app_name = 'blog'
urlpatterns = [
    path('', BlogsView.as_view(), name='show-blogs'),
    path('search/', SearchBlogsView.as_view(), name='show-blogs-by-search'),
    path('search/<slug>', BlogsViewByCategoriesOrTags.as_view(), name='show-blogs-by-query'),
    path('<blog_id>', blog_detail_view, name='show-blog-detail'),
]

tinakala/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.views.decorators.cache import never_cache
from ckeditor_uploader import views as ckeditor_views

from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from .settings import (
    DEBUG,
    STATIC_URL,
    STATIC_ROOT,
    MEDIA_URL,
    MEDIA_ROOT,
)
from .views import (
    home_page,
)

urlpatterns = [
    # reset password urls
    path('password-reset/', PasswordResetView.as_view(
        template_name='accounts/reset_password/password_reset.html'), name='password_reset'),
    path('password-reset/done/', PasswordResetDoneView.as_view(
        template_name='accounts/reset_password/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name='accounts/reset_password/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(
        template_name='accounts/reset_password/password_reset_complete.html'), name='password_reset_complete'),
    # admin panel urls
    path('admin/', admin.site.urls),
    # ckeditor path
    url(r'^ckeditor/upload/', login_required(ckeditor_views.upload), name='ckeditor_upload'),
    url(r'^ckeditor/browse/', never_cache(login_required(ckeditor_views.browse)), name='ckeditor_browse'),
    # main application urls
    path('', home_page, name='home-page'),
    path('', include('shop_accounts.urls', namespace='auth')),
    path('', include('shop_settings.urls', namespace='info')),
    path('', include('shop_contact.urls', namespace='contact')),
    path('blog/', include('shop_blog.urls', namespace='blog')),
    path('products/', include('shop_products.urls', namespace='products')),
    path('cart/', include('shop_cart.urls', namespace='cart')),
    path('order/', include('shop_order.urls', namespace='order')),
]
if DEBUG:
    urlpatterns += static(STATIC_URL, document_root=STATIC_ROOT)
    urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

shop_blog/models.py
from datetime import datetime

from django.contrib.auth.models import User
from django.db import models
from django.db.models import Q
from django.db.models.signals import pre_save
from django.dispatch import receiver

from ckeditor_uploader.fields import RichTextUploadingField
from django_resized import ResizedImageField

from tinakala.utils import unique_slug_generator, upload_blog_avatar


class BlogCategory(models.Model):
    fa_title = models.CharField(max_length=100, verbose_name='عنوان دسته')
    title = models.CharField(max_length=100, verbose_name='عنوان انگلیسی دسته')
    slug = models.SlugField(null=True, blank=True, verbose_name='عنوان در آدرس')

    class Meta:
        verbose_name = 'دسته بندی'
        verbose_name_plural = 'مدیریت دسته بندی'

    def __str__(self):
        return self.fa_title


@receiver(pre_save, sender=BlogCategory)
def blog_pre_save_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)


class BlogTag(models.Model):
    fa_title = models.CharField(max_length=100, verbose_name='عنوان تگ')
    title = models.CharField(max_length=100, verbose_name='عنوان انگلیسی تگ')
    slug = models.SlugField(null=True, blank=True, verbose_name='عنوان در آدرس')

    class Meta:
        verbose_name = 'تگ'
        verbose_name_plural = 'مدیریت تگ ها'

    def __str__(self):
        return self.fa_title


@receiver(pre_save, sender=BlogTag)
def product_pre_save_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)


class BlogManager(models.Manager):
    def get_blog_by_category_or_tag(self, query):
        lookup = (
                Q(categories__slug__iexact=query) |
                Q(tags__slug__iexact=query)
        )
        return self.get_queryset().filter(lookup).distinct()

    def get_blog_by_search(self, query):
        lookup = (
                Q(categories__fa_title__icontains=query) |
                Q(categories__title__icontains=query) |
                Q(tags__fa_title__icontains=query) |
                Q(tags__title__icontains=query) |
                Q(title__icontains=query) |
                Q(content__iexact=query) |
                Q(author__first_name__icontains=query) |
                Q(author__last_name__icontains=query)
        )
        return self.get_queryset().filter(lookup).distinct()


class Blog(models.Model):
    author = models.ForeignKey(User, on_delete=models.PROTECT, verbose_name='نویسنده')
    title = models.CharField(max_length=150, verbose_name='عنوان مقاله')
    content = RichTextUploadingField(verbose_name='محتوای مقاله')
    avatar = ResizedImageField(size=[360, 225], quality=150, crop=['middle', 'center'], upload_to=upload_blog_avatar, verbose_name='آواتار مقاله')
    timestamp = models.DateTimeField(default=datetime.now(), verbose_name='زمان ارسال')
    categories = models.ManyToManyField(BlogCategory, verbose_name='مربوط به دسته بندی های')
    tags = models.ManyToManyField(BlogTag, verbose_name='مربوط به تگ های')

    objects = BlogManager()

    class Meta:
        verbose_name = 'مقاله'
        verbose_name_plural = 'مدیریت مقالات'

    def __str__(self):
        return f'{self.author.get_full_name()}-{self.title}'


class BlogViewManager(models.Manager):
    def blog_view_by_user(self, user, blog):
        return self.get_queryset().filter(user=user, blog=blog).first()

    def blog_view_counts(self, blog):
        return self.get_queryset().filter(blog=blog).count()


class BlogView(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, verbose_name='بلاگ')
    user = models.CharField(max_length=15, verbose_name='آی پی بازدید کننده')

    objects = BlogViewManager()

    class Meta:
        verbose_name = 'ویوی بلاگ'
        verbose_name_plural = 'مدیریت ویو بلاگ ها'

    def __str__(self):
        return f'{self.blog}-{self.user}'

shop_blog/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView

from pure_pagination.mixins import PaginationMixin

from shop_blog.models import BlogTag, BlogCategory, Blog, BlogView
from tinakala.utils import get_visitor_ip_address


class BlogsView(PaginationMixin, ListView):
    template_name = 'blog/SiteBlog.html'
    paginate_by = 8
    queryset = Blog.objects.all().order_by('-timestamp')


class SearchBlogsView(PaginationMixin, ListView):
    template_name = 'blog/SiteBlog.html'
    paginate_by = 8

    def get_queryset(self):
        query = self.request.GET.get('query')
        if query is not None:
            return Blog.objects.get_blog_by_search(query=query).order_by('-timestamp')
        else:
            return Blog.objects.all().order_by('-timestamp')


class BlogsViewByCategoriesOrTags(PaginationMixin, ListView):
    template_name = 'blog/SiteBlog.html'
    paginate_by = 8

    def get_queryset(self):
        slug = self.kwargs.get('slug')
        return Blog.objects.get_blog_by_category_or_tag(query=slug).order_by('-timestamp')


def newest_blog_view(request, *args, **kwargs):
    newest_blogs = Blog.objects.all()[:5]
    context = {
        'newest_blogs': newest_blogs,
    }
    return render(request, 'blog/components/blog_newest_blog.html', context)


def categories_blog_view(request, *args, **kwargs):
    categories = BlogCategory.objects.all()
    context = {
        'categories': categories,
    }
    return render(request, 'blog/components/blog_categories.html', context)


def tags_blog_view(request, *args, **kwargs):
    tags = BlogTag.objects.all()
    context = {
        'tags': tags,
    }
    return render(request, 'blog/components/blog_tags.html', context)


def blog_detail_view(request, blog_id):
    blog = get_object_or_404(Blog, pk=blog_id)
    categories = blog.categories.all()

    user = get_visitor_ip_address(request=request)
    if user['valid']:
        view = BlogView.objects.blog_view_by_user(user=user['ip'], blog=blog)
        if not view:
            view = BlogView.objects.create(blog=blog, user=user['ip'])
            view.save()

    views = BlogView.objects.blog_view_counts(blog=blog)

    context = {
        'blog': blog,
        'categories': categories,
        'views': views,
    }
    return render(request, 'blog/SiteBlogDetail.html', context)

shop_blog/templates/blog/components/blog_categories.html
<div class="dt-sn dt-sl mb-3">
    <div class="section-title text-sm-title title-wide no-after-title-wide mb-1">
        <h2>دسته ها</h2>
    </div>
    <ul class="category-list">
        {% for category in categories %}
            <li><a href="{% url 'blog:show-blogs-by-query' category.slug %}">{{ category.fa_title }}</a></li>
        {% endfor %}
    </ul>
</div>

shop_blog/templates/blog/components/blog_newest_blog.html
{% load jalali_tags %}
<div class="widget-posts dt-sn dt-sl mb-3 pt-4">
    <div class="col-12 mb-3 mt-1">
        <div class="widget-search">
            <form action="{% url 'blog:show-blogs-by-search' %}" method="get">
                <input type="text" name="query" placeholder="نام مقاله یا نویسنده مورد نظر را بنویسید...">
                <button class="btn-search-widget" type="submit">
                    <img src="/site_static/app_site/img/theme/search.png" alt="">
                </button>
            </form>
        </div>
    </div>
</div>

<div class="widget-posts dt-sn dt-sl mb-3">
    <div class="title-sidebar dt-sl mb-3">
        <h3>جدیدترین نوشته ها</h3>
    </div>
    <div class="content-sidebar dt-sl">
        {% for newest_blog in newest_blogs %}
            <div class="item">
                <div class="item-inner">
                    <div class="item-thumb">
                        <a href="{% url 'blog:show-blog-detail' newest_blog.id %}" class="img-holder" style="background-image: url({{ newest_blog.avatar.url }})"></a>
                    </div>
                    <p class="title">
                        <a href="{% url 'blog:show-blog-detail' newest_blog.id %}">{{ newest_blog.title }}</a>
                    </p>
                    <div class="item-meta">
                        <span class="time">{{ newest_blog.timestamp|to_jalali:'%Y/%m/%d' }}</span>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>

shop_blog/templates/blog/components/blog_tags.html
<div class="dt-sn dt-sl">
    <div class="section-title text-sm-title title-wide no-after-title-wide mb-1">
        <h2>برچسبها</h2>
    </div>
    <ul class="tag-list">
        {% for tag in tags %}
            <li><a href="{% url 'blog:show-blogs-by-query' tag.slug %}">{{ tag.fa_title }}</a></li>
        {% endfor %}
    </ul>
</div>