shop_accounts/urls.py
from django.urls import path

from shop_accounts.views import (
    login_user,
    logout_user,
    register_user,
    user_reset_password,
    user_change_profile,
    user_verify_phone,
    user_send_otp,
    user_profile,
    user_address,
    user_address_detail,
    user_address_delete,
    user_get_cities_of_state,
    user_favorite,
    user_favorite_add,
    user_favorite_delete,
    user_comment,
    user_comment_positive_vote,
    user_comment_negative_vote,
    user_comment_delete,
    user_ticket,
    user_create_ticket,
    user_ticket_detail,
    user_orders,
    user_order_detail,
    LastVisitedView,
)

app_name = 'auth'
urlpatterns = [
    # User Authentication Methods
    path('auth/login', login_user, name='login'),
    path('auth/logout', logout_user, name='logout'),
    path('auth/register', register_user, name='register'),
    path('auth/reset-password', user_reset_password, name='reset-password'),
    # User Profile Methods
    path('account/user-panel', user_profile, name='user-profile'),
    path('account/user-change-profile', user_change_profile, name='change-profile'),
    path('account/user-send-otp', user_send_otp, name='send-otp'),
    path('account/user-verify-phone', user_verify_phone, name='verify-phone'),
    # User Profile Address Methods
    path('account/user-address', user_address, name='user-address'),
    path('account/user-address/<int:address_id>/edit', user_address_detail, name='user-address-edit'),
    path('account/user-address/<int:address_id>/delete', user_address_delete, name='user-address-delete'),
    path('account/user-get-cities-of-state', user_get_cities_of_state, name='user-get-cities-of-state'),
    # User Profile Favorite Methods
    path('account/user-favorite', user_favorite, name='user-favorite'),
    path('account/user-favorite/<slug>/add', user_favorite_add, name='user-favorite-add'),
    path('account/user-favorite/<slug>/delete', user_favorite_delete, name='user-favorite-delete'),
    # User Profile Comment Methods
    path('account/user-comment', user_comment, name='user-comment'),
    path('account/user-comment/<comment_id>/delete', user_comment_delete, name='user-comment-delete'),
    path('account/user-comment/<comment_id>/pos-vote', user_comment_positive_vote, name='user-comment-positive-vote'),
    path('account/user-comment/<comment_id>/neg-vote', user_comment_negative_vote, name='user-comment-negative-vote'),
    # User Profile Ticket Methods
    path('account/ticket', user_ticket, name='user-ticket'),
    path('account/ticket/add', user_create_ticket, name='user-add-ticket'),
    path('account/ticket/<ticket_id>', user_ticket_detail, name='user-ticket-show'),
    # User Orders Methods
    path('account/invoice', user_orders, name='user-invoice'),
    path('account/invoice/<str:order_code>', user_order_detail, name='user-invoice-detail'),
    # User Last Visited Product Methods
    path('recent-visits', LastVisitedView.as_view(), name='recent-visits'),
]

shop_order/urls.py
from django.urls import path

from shop_order.views import *

app_name = 'order'
urlpatterns = [
    path('check-out', cart_check_out, name='check-out'),
    path('to-bank/<str:order_code>/', to_bank, name='to-bank'),
    path('call-back', call_back, name='call-back'),
]

shop_products/urls.py
from django.urls import path

from .views import (
    search_products_view,
    get_product_amazing,
    detail_product_view,
    get_product_by_brand_view,
    search_product_by_category_view,
)

app_name = 'products'
urlpatterns = [
    path('search/', search_products_view, name='search'),
    path('search/suggested/', get_product_amazing, name='suggested'),
    path('search/<category>', search_product_by_category_view, name='search_by_category'),
    path('search/brand/<brand>', get_product_by_brand_view, name='product_by_brand'),
    path('<product_code>/<product_slug>', detail_product_view, name='detail_product'),
]

tinakala/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.views.decorators.cache import never_cache
from ckeditor_uploader import views as ckeditor_views

from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from .settings import (
    DEBUG,
    STATIC_URL,
    STATIC_ROOT,
    MEDIA_URL,
    MEDIA_ROOT,
)
from .views import (
    home_page,
)

urlpatterns = [
    # reset password urls
    path('password-reset/', PasswordResetView.as_view(
        template_name='accounts/reset_password/password_reset.html'), name='password_reset'),
    path('password-reset/done/', PasswordResetDoneView.as_view(
        template_name='accounts/reset_password/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name='accounts/reset_password/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(
        template_name='accounts/reset_password/password_reset_complete.html'), name='password_reset_complete'),
    # admin panel urls
    path('admin/', admin.site.urls),
    # ckeditor path
    url(r'^ckeditor/upload/', login_required(ckeditor_views.upload), name='ckeditor_upload'),
    url(r'^ckeditor/browse/', never_cache(login_required(ckeditor_views.browse)), name='ckeditor_browse'),
    # main application urls
    path('', home_page, name='home-page'),
    path('', include('shop_accounts.urls', namespace='auth')),
    path('', include('shop_settings.urls', namespace='info')),
    path('', include('shop_contact.urls', namespace='contact')),
    path('blog/', include('shop_blog.urls', namespace='blog')),
    path('products/', include('shop_products.urls', namespace='products')),
    path('cart/', include('shop_cart.urls', namespace='cart')),
    path('order/', include('shop_order.urls', namespace='order')),
]
if DEBUG:
    urlpatterns += static(STATIC_URL, document_root=STATIC_ROOT)
    urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

shop_accounts/views/views_address.py
"""
shop_accounts -> views -> user address methods
"""
from django.http import JsonResponse, Http404
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods

from shop_settings.models import City
from tinakala.utils import profile_completion_required

from shop_accounts.models import (
    UserProfile,
    UserAddress,
)
from shop_accounts.forms import (
    UserAddressForm,
)

"""
shop_accounts -> profile address load/create methods
"""


@login_required(login_url='auth:login')
@profile_completion_required(profile_model=UserProfile, redirected_path='auth:change-profile')
def user_address(request):
    address_form = UserAddressForm(request.POST or None, request=request)
    active_addresses: UserAddress = UserAddress.objects.filter(user_id=request.user.id, is_active=True)
    if address_form.is_valid():
        user_new_address = UserAddress.objects.create(
            user=request.user,
            fullname=address_form.cleaned_data.get('fullname'),
            phone=address_form.cleaned_data.get('phone'),
            state=address_form.cleaned_data.get('state'),
            city=address_form.cleaned_data.get('city'),
            address=address_form.cleaned_data.get('address'),
            postal_code=address_form.cleaned_data.get('postal_code'),
            plaque=address_form.cleaned_data.get('plaque'),
        )
        user_new_address.save()
        address_form = UserAddressForm()
        messages.success(request, 'آدرس شما با موفقیت ثبت شد.')
        return redirect('auth:user-address')
    context = {
        'active_addresses': active_addresses,
        'address_form': address_form,
    }
    return render(request, 'accounts/SiteAddress.html', context)


@require_http_methods(['GET', ])
@login_required(login_url='auth:login')
@profile_completion_required(profile_model=UserProfile, redirected_path='auth:change-profile')
def user_get_cities_of_state(request):
    state_id = request.GET.get('state_id')
    cities = City.objects.filter(state_id=state_id).order_by('city').values()
    return JsonResponse(list(cities), safe=False)


"""
shop_accounts -> profile address updating methods
"""


@login_required(login_url='auth:login')
@profile_completion_required(profile_model=UserProfile, redirected_path='auth:change-profile')
def user_address_detail(request, address_id):
    address: UserAddress = get_object_or_404(klass=UserAddress, pk=address_id, is_active=True, user=request.user)
    address_form = UserAddressForm(request.POST or None, request=request, initial={
        'fullname': address.fullname,
        'phone': address.phone,
        'state': address.state,
        'city': address.city,
        'address': address.address,
        'postal_code': address.postal_code,
        'plaque': address.plaque,
    })
    if address_form.is_valid():
        address.fullname = address_form.cleaned_data.get('fullname')
        address.phone = address_form.cleaned_data.get('phone')
        address.state = address_form.cleaned_data.get('state')
        address.city = address_form.cleaned_data.get('city')
        address.address = address_form.cleaned_data.get('address')
        address.postal_code = address_form.cleaned_data.get('postal_code')
        address.plaque = address_form.cleaned_data.get('plaque')
        address.is_active = True
        address.save()
        messages.success(request, 'بروزرسانی آدرس با موفقیت انجام شد.')
        return redirect('auth:user-address')
    context = {
        'address_id': address.id,
        'address_form': address_form,
    }
    return render(request, 'accounts/SiteAddressDetail.html', context)


@login_required(login_url='auth:login')
@profile_completion_required(profile_model=UserProfile, redirected_path='auth:change-profile')
def user_address_delete(request, address_id):
    address: UserAddress = get_object_or_404(klass=UserAddress, pk=address_id)
    if address.user != request.user:
        return Http404('آدرسی با این مشخصات برای شما وجود ندارد.')
    address.is_active = False
    address.save()
    messages.success(request, 'آدرس شما با موفقیت حذف شد.')
    return redirect('auth:user-address')

shop_accounts/views/views_comment.py
"""
shop_accounts -> views -> user comment manager methods
"""
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.shortcuts import render, get_object_or_404, redirect

from pure_pagination import Paginator, PageNotAnInteger

from shop_accounts.models import UserProfile, UserCommentVote
from shop_products.models import ProductComment
from tinakala.utils import profile_completion_required, get_total_average


@login_required(login_url='auth:login')
@profile_completion_required(profile_model=UserProfile, redirected_path='auth:change-profile')
def user_comment(request):
    try:
        page = request.GET.get('page', 1)
    except PageNotAnInteger:
        page = 1

    comments = []
    for comment in ProductComment.objects.filter(user=request.user, promote=True):
        total_avg = ProductComment.objects.filter(product=comment.product).values_list('worth', 'quality', 'function')
        comments.append({
            'id': comment.id,
            'title': comment.title,
            'comment': comment.comment,
            'verified': comment.verified,
            'positive': comment.usercommentvote_set.filter(vote=True).count(),
            'negative': comment.usercommentvote_set.filter(vote=False).count(),
            'product_code': comment.product.code,
            'product_slug': comment.product.slug,
            'product_avatar': comment.product.avatar.url,
            'product_avg': get_total_average(total_avg),
        })

    context = {
        'comments': Paginator(comments, request=request, per_page=8).page(page),
    }
    return render(request, 'accounts/SiteUserComment.html', context)


@login_required(login_url='auth:login')
@profile_completion_required(profile_model=UserProfile, redirected_path='auth:change-profile')
def user_comment_delete(request, *args, **kwargs):
    comment_id = kwargs.get('comment_id')
    comment = get_object_or_404(ProductComment, id=comment_id)
    if not comment.promote:
        raise Http404('کامنتی یافت نشد')
    comment.promote = False
    comment.save()
    messages.success(request, f'نظر شما با موفقیت حذف شد.')
    return redirect('auth:user-comment')


@login_required(login_url='auth:login')
@profile_completion_required(profile_model=UserProfile, redirected_path='auth:change-profile')
def user_comment_positive_vote(request, *args, **kwargs):
    comment_id = kwargs.get('comment_id')
    comment = get_object_or_404(ProductComment, id=comment_id)
    existed_user_vote: UserCommentVote = UserCommentVote.objects.filter(user=request.user, comment=comment).first()
    if existed_user_vote:
        existed_user_vote.positive_comment_vote()
    else:
        existed_user_vote = UserCommentVote.objects.create(user=request.user, comment=comment, vote=True)
        existed_user_vote.save()
    messages.success(request, f'نظر مثبت شما برای کامنت ({comment.user.get_full_name()}) با موفقیت ثبت شد.')
    return redirect('auth:user-profile')


@login_required(login_url='auth:login')
@profile_completion_required(profile_model=UserProfile, redirected_path='auth:change-profile')
def user_comment_negative_vote(request, *args, **kwargs):
    comment_id = kwargs.get('comment_id')
    comment = get_object_or_404(ProductComment, id=comment_id)
    existed_user_vote: UserCommentVote = UserCommentVote.objects.filter(user=request.user, comment=comment).first()
    if existed_user_vote:
        existed_user_vote.negative_comment_vote()
    else:
        existed_user_vote = UserCommentVote.objects.create(user=request.user, comment=comment, vote=False)
        existed_user_vote.save()
    messages.success(request, f'نظر منفی شما برای کامنت ({comment.user.get_full_name()}) با موفقیت ثبت شد.')
    return redirect('auth:user-profile')

shop_accounts/views/views_favorite.py
"""
shop_accounts -> views -> user favorite methods
"""
from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from pure_pagination import Paginator, PageNotAnInteger

from shop_accounts.models import UserProfile, UserFavorite
from shop_products.models import Product, ProductComment
from tinakala.utils import profile_completion_required, create_products_object_list


@login_required(login_url='auth:login')
@profile_completion_required(profile_model=UserProfile, redirected_path='auth:change-profile')
def user_favorite(request, *args, **kwargs):
    try:
        page = request.GET.get('page', 1)
    except PageNotAnInteger:
        page = 1

    favorites: UserFavorite = UserFavorite.objects.filter(user=request.user, product__is_active=True).first()
    favorites = create_products_object_list(favorites.product.all(), model=ProductComment) if favorites else []

    context = {
        'favorites': Paginator(favorites, per_page=10, request=request).page(page),
    }
    return render(request, 'accounts/SiteUserFavorite.html', context)


@login_required(login_url='auth:login')
@profile_completion_required(profile_model=UserProfile, redirected_path='auth:change-profile')
def user_favorite_add(request, *args, **kwargs):
    slug = kwargs['slug']
    product = Product.objects.filter(slug=slug).first()
    if product:
        user_favorite_object: UserFavorite = UserFavorite.objects.filter(user=request.user).first()
        if user_favorite_object:
            user_favorite_object.product.add(product)
            user_favorite_object.save()
            message = 'این کالا با موفقیت به لیست علاقه مندی شما اضافه شد.'
        else:
            user_favorite_object = UserFavorite.objects.create(user=request.user)
            user_favorite_object.product.add(product)
            user_favorite_object.save()
            message = 'این کالا با موفقیت به لیست علاقه مندی شما اضافه شد.'
        result = True
    else:
        result = False
        message = f'کالایی با عنوان <<{slug}>> یافت نشد.'
    return JsonResponse([message, result], safe=False)


@login_required(login_url='auth:login')
@profile_completion_required(profile_model=UserProfile, redirected_path='auth:change-profile')
def user_favorite_delete(request, *args, **kwargs):
    slug = kwargs['slug']
    favorite: UserFavorite = get_object_or_404(UserFavorite, user=request.user)
    product = get_object_or_404(Product, slug=slug)
    if favorite:
        favorite.product.remove(product)
        favorite.save()
        messages.success(request, f'کالای <<{product.title}>> از لیست علاقه مندی با موفقیت حذف گردید.')
    else:
        messages.error(request, f'کالایی با عنوان {slug} در لیست علاقه مندی شما موجود نمی باشد.')
    return redirect('auth:user-favorite')

shop_accounts/views/views_visited.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView

from pure_pagination import PaginationMixin

from shop_products.models import ProductVisit


class LastVisitedView(PaginationMixin, LoginRequiredMixin, ListView):
    template_name = 'accounts/SiteUserLastVisited.html'
    paginate_by = 10

    def get_queryset(self):
        return ProductVisit.objects.get_product_by_user(user=self.request.user)[:8]

shop_accounts/templates/accounts/SiteLogin.html
{% extends 'accounts/shared/_AccountsMainLayout.html' %}
{% block content %}
    <main class="main-content dt-sl mt-4 mb-3">
        <div class="container main-container">

            <div class="row">
                <div class="col-xl-4 col-lg-5 col-md-7 col-12 mx-auto">
                    <div class="form-ui dt-sl dt-sn pt-4">
                        <div class="section-title title-wide mb-1 no-after-title-wide">
                            <h2 class="font-weight-bold">ورود به  تیناکالا</h2>
                        </div>
                        {% if messages %}
                            <div class="alert alert-success w-100">
                                {% for message in messages %}
                                    <p style="font-size: 15px" class="my-auto p-2 text-right">{{ message }}</p>
                                {% endfor %}
                            </div>
                        {% endif %}
                        <form action="" method="post">
                            {% csrf_token %}
                            <div class="form-row-title">
                                <h3>{{ login_form.username_email.label }}</h3>
                            </div>
                            <div class="form-row with-icon">
                                {{ login_form.username_email }}
                                <i class="mdi mdi-account-circle-outline"></i>
                            </div>
                            <div class="form-row-title">
                                <h3>{{ login_form.password.label }}</h3>
                            </div>
                            <div class="form-row with-icon">
                                {{ login_form.password }}
                                <i class="mdi mdi-lock-open-variant-outline"></i>
                                {# Start Display Errors To User #}
                                {% for error in login_form.username_email.errors %}
                                    <p class="text-danger mt-2">{{ error }}</p>
                                {% endfor %}
                                {# End Display Errors To User #}
                            </div>
                            <div class="form-row mt-2">
                                <div class="custom-control custom-checkbox float-right mt-2">
                                    {{ login_form.remember_me }}
                                    <label class="custom-control-label" for="{{ login_form.remember_me.id_for_label }}">
                                        مرا به خاطر بسپار
                                    </label>
                                </div>
                            </div>
                            <br>
                            <div class="form-row">
                                {{ login_form.captcha }}
                                {% for error in login_form.captcha.errors %}
                                    <p class="text-danger mt-2">{{ error }}</p>
                                {% endfor %}
                            </div>

                            <div class="form-row mt-3">
                                <button class="btn-primary-cm btn-with-icon mx-auto w-100">
                                    <i class="mdi mdi-login-variant"></i>
                                    ورود به  تیناکالا
                                </button>
                            </div>
                            <div class="form-footer text-right mt-3">
                                <span class="d-block font-weight-bold">کاربر جدید هستید؟</span>
                                <a href="{% url 'auth:register' %}" class="d-inline-block mr-3 mt-2">ثبت نام در  تیناکالا</a>
                                <a href="{% url 'password_reset' %}" class="d-inline-block mr-3 mt-2">رمز عبور خود را فراموش کرده اید؟</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>

        </div>
    </main>
{% endblock %}

shop_accounts/templates/accounts/SiteUserComment.html
{% extends 'app_site/shared/_SiteMainLayout.html' %}
{% load static %}
{% load render_partial %}
{% block content %}
    <main class="main-content dt-sl mt-4 mb-3" style="transform: none;">
        <div class="container main-container" style="transform: none;">
            <div class="row" style="transform: none;">

                <!-- Start Sidebar -->
                <div class="col-xl-3 col-lg-4 col-md-4 col-sm-12 order-lg-1" style="position: relative; overflow: visible; box-sizing: border-box; min-height: 1px;">
                    <div class="theiaStickySidebar" style="padding-top: 0px; padding-bottom: 1px; position: static; transform: none; top: 0px; left: 74.6px;">
                        <div class="profile-sidebar dt-sl">
                            {% render_partial 'shop_accounts.views.user_profile_panel' %}
                            {% render_partial 'shop_accounts.views.user_profile_sidebar_menu' %}
                        </div>
                        <div class="resize-sensor" style="position: absolute; left: 0px; top: 0px; right: 0px; bottom: 0px; overflow: hidden; z-index: -1; visibility: hidden;">
                            <div class="resize-sensor-expand" style="position: absolute; left: 0; top: 0; right: 0; bottom: 0; overflow: hidden; z-index: -1; visibility: hidden;">
                                <div style="position: absolute; left: 0px; top: 0px; transition: all 0s ease 0s; width: 360px; height: 770px;">
                                </div>
                            </div>
                            <div class="resize-sensor-shrink" style="position: absolute; left: 0; top: 0; right: 0; bottom: 0; overflow: hidden; z-index: -1; visibility: hidden;">
                                <div style="position: absolute; left: 0; top: 0; transition: 0s; width: 200%; height: 200%"></div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- End Sidebar -->

                <!-- Start Content -->
                <div class="col-xl-9 col-lg-8 col-md-8 col-sm-12">
                    {% if messages %}
                        {% for message in messages %}
                            <div class="alert
                            alert-{% if message.tags == 'error' %}danger{% elif message.tags == 'success' %}success{% else %}primary{% endif %}
                            w-100 mb-2">
                                <p style="font-size: 15px">{{ message }}</p>
                            </div>
                        {% endfor %}
                    {% endif %}
                    <div class="row">
                        <div class="col-12">
                            <div class="section-title text-sm-title title-wide mb-1 no-after-title-wide dt-sl mb-2 px-res-1">
                                <h2>نقد و نظرات</h2>
                            </div>
                            <div class="dt-sl">
                                <div class="row">
                                    {% if comments %}
                                        {% for comment in comments.object_list %}
                                            <div class="col-lg-6 col-md-12">
                                                <div class="card-horizontal-product">
                                                    <div class="card-horizontal-product-thumb">
                                                        <a href="{% url 'products:detail_product' comment.product_code comment.product_slug %}">
                                                            <img src="{{ comment.product_avatar }}" alt="">
                                                        </a>
                                                        <small class="font-weight-bold">امتیاز من به محصول</small>
                                                        <div class="rating-stars">
                                                            {% for star in comment.product_avg %}
                                                                <i class="mdi mdi-star {{ star|yesno:'active,' }}"></i>
                                                            {% endfor %}
                                                        </div>
                                                    </div>
                                                    <div class="card-horizontal-product-content">
                                                        <div class="label-status-{{ comment.verified|yesno:'comment,denied' }}">{{ comment.verified|yesno:"تایید شده,تایید نشده" }}</div>
                                                        <div class="card-horizontal-comment-title">
                                                            <a href="{% url 'products:detail_product' comment.product_code comment.product_slug %}">
                                                                <h3>{{ comment.title }}</h3>
                                                            </a>
                                                        </div>
                                                        <div class="card-horizontal-comment">
                                                            <p>{{ comment.comment }}</p>
                                                        </div>
                                                        <div class="card-horizontal-product-buttons">
                                                            <div class="float-right">
                                                            <span class="count-like">
                                                                <i class="mdi mdi-thumb-up-outline"></i>
                                                                {{ comment.positive }}
                                                            </span>
                                                                <span class="count-like">
                                                                <i class="mdi mdi-thumb-down-outline"></i>
                                                                    {{ comment.negative }}
                                                            </span>
                                                            </div>
                                                            <a href="{% url 'auth:user-comment-delete' comment.id %}" class="btn btn-light">حذف</a>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        {% endfor %}

                                    {% else %}
                                        <div class="container-fluid bg-white">
                                            <div class="alert alert-warning btn-block mt-3">
                                                نظری توسط حساب شما ثبت نشده است.
                                            </div>
                                        </div>
                                    {% endif %}
                                </div>
                                {% ifnotequal comments.pages|length 1 %}
                                    {% include 'app_site/shared/pagination/_GenericPagination.html' with page_obj=comments %}
                                {% endifnotequal %}
                            </div>
                        </div>
                    </div>
                </div>
                <!-- End Content -->

            </div>
        </div>
    </main>
{% endblock %}